name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.2.0a2]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: View poetry --help
      run: poetry --help
    - name: install dependencys
      run: | 
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi
    - name: Analysing the code with pylint
      run: |
        pylint src/* --disable=fixme
